# Generated by Django 4.2.3 on 2023-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('Book', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=100)),
                ('Gmail', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
            ],
        ),
    ]
